from .base import BaseDTO
from .access_log import AccessLogDTO
from .audit_log import AuditLogDTO
from .autobase import AutobaseDTO
from .document import DocumentDTO
from .efficiency_metric import EfficiencyMetricDTO
from .financial_transaction import FinancialTransactionDTO
from .fuel_type import FuelTypeDTO
from .gas_station import GasStationDTO
from .gas_station_contract_orm import GasStationContractDTO
from .gas_station_fuel_orm import GasStationFuelDTO
from .gps_track import GpsTrackDTO
from .maintenance_log import MaintenanceLogDTO
from .ml_suggestion import MlSuggestionDTO
from .part_inventory import PartInventoryDTO
from .refueling_log import RefuelingLogDTO
from .repair_request import RepairRequestDTO
from .report import ReportDTO
from .role import RoleDTO
from .route import RouteDTO
from .schedule import ScheduleDTO
from .scheduled_task import ScheduledTaskDTO
from .storage_fuel import StorageFuelDTO
from .supplier import SupplierDTO
from .system_event import SystemEventDTO
from .user import UserDTO
from .vehicle import VehicleDTO
